"""empty message

Revision ID: 5801319fab95
Revises: 3249ad395d26
Create Date: 2021-05-16 23:47:37.878642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5801319fab95'
down_revision = '3249ad395d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['holiday_id'], ['holidays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markers')
    # ### end Alembic commands ###
