"""empty message

Revision ID: 8ad3abe1ec11
Revises: 
Create Date: 2021-05-17 06:05:13.270184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ad3abe1ec11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('position_lat', sa.Numeric(), nullable=False))
    op.add_column('markers', sa.Column('position_long', sa.Numeric(), nullable=False))
    op.drop_column('markers', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('position', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('markers', 'position_long')
    op.drop_column('markers', 'position_lat')
    # ### end Alembic commands ###
